### ISSUE TITLE
Invalid HTML in TOC of User Manual

### ISSUE THREAD

**Issue by celtic-coder** [pml-lang/user-manual#6]
Hi Christian (@pml-lang),

I was checking the [User Manual](https://www.pml-lang.dev/docs/user_manual/index.html) on the [W3C Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.pml-lang.dev%2Fdocs%2Fuser_manual%2Findex.html&checkerrorpages=yes&showsource=yes&showoutline=yes) website and noticed that there were two main issues:

### (1) `<li>` tags within `<div>` tags

The error is showing as "_Element [li](https://html.spec.whatwg.org/multipage/#the-li-element) not allowed as child of element [div](https://html.spec.whatwg.org/multipage/#the-div-element) in this context_".  This can be seen in the screenshot showing the Table of Contents:

![li-errors-in-TOC](https://user-images.githubusercontent.com/11787866/114786557-3670dc80-9d76-11eb-939f-bc5d24a9c9a0.png)

In contrast to the three list items in error, the section immediately below shows the list items are properly enclosed in the unordered list tags (`<ul>` and `<\ul>`).

Might this be, perhaps, because no child elements exist in chapters 1 and 2?

### (2) `<h1>` tag is missing (confusing error)

At the bottom of the validator output is the **Heading-level outline:**

![Heading-level-outline](https://user-images.githubusercontent.com/11787866/114787878-602b0300-9d78-11eb-80f5-d83cb62de569.png)

The outline is useful as it shows the organization of the document. But the error message is confusing as it saying the  `<h1>` tag is missing. This is not the case, as the `<h1>` (**PML User Manual**) is immediately below the `<h2>` (**Table of Contents**) in the outline.

However, this raises a question: should not the order be reversed? Doesn't the document title have a higher precedence than the table of contents for the document? This is turn would resolve the validator's issue with the missing `<h1>` tag.

Kind Regards,
Liam

**Comment by pml-lang** [comment]
> checking the User Manual on the W3C Validator website

Good idea! Thank you.

(1)
> `<li>` tags within `<div>` tags
> Might this be, perhaps, because no child elements exist in chapters 1 and 2?

The reason is that I totally forgot to embed the first level `li` tags in an `ul`. It's now fixed and will be integrated in the next version of PML.

(2)
> tag is missing (confusing error)

Using `h2` for the TOC title is correct because the TOC is part of the whole document, one level below the document title (which is `h1`).

In this case the validator reports an error, because of the layout. The TOC is displayed in an `aside` without a preceding `h1`.
If the TOC were displayed at the top (with PML option `TOC_position=top`) then the validator wouldn't report an error, because the TOC would be a child in the document's text. Therefore I think that this is a false positive in this given situation.

One could avoid this error report, for example by using a `div` for the TOC title, but that would be 'a hack to satisfy the validator'.

Therefore I think nothing should be changed.
